### ISSUE TITLE
Procure Camera(s)

### ISSUE THREAD

**Issue by nrubera** [nicholaslamon/CNCS_Capstone#19]

**Comment by nicholaslamon** [comment]
For a camera solution, we are going to be using a camera that will attach to our Pi, which will be interesting to figure out. It also might be easier to access in comparison to buying a camera. Most cameras only allow footage to be accessed via the vendor's cloud solution, rather than our own.

**Comment by nicholaslamon** [comment]
https://projects.raspberrypi.org/en/projects/getting-started-with-picamera/2

**Comment by KyleWebster46** [comment]
https://zoneminder.com/

**Comment by KyleWebster46** [comment]
https://hub.docker.com/r/migoller/shinobidocker
