### ISSUE TITLE
Create and Setup VPN Access

### ISSUE THREAD

**Issue by nicholaslamon** [nicholaslamon/CNCS_Capstone#2]
Create inbound and outbound rules to allow remote computers (Kyle & Nick L) to access the network.

Research Unifi VPN and how it operates (I believe it's called teleport).

**Comment by nrubera** [comment]
Unifi Teleport has been setup to allow for remote access to the Unifi console network.

![image](https://user-images.githubusercontent.com/70775749/219899694-9ff13271-a522-4f85-aebe-48a1a8de17d4.png)
