### ISSUE TITLE
Setup and Cable Unifi Router

### ISSUE THREAD

**Issue by nrubera** [nicholaslamon/CNCS_Capstone#20]

**Comment by nrubera** [comment]
Router has been setup and cabled up to ISP modem. 

![image](https://user-images.githubusercontent.com/70775749/215344454-e14d7d9f-bf20-4696-a8f5-b5ed3a5a588a.png)


Snip of router Setup page.

![image](https://user-images.githubusercontent.com/70775749/215344504-147839d4-9472-422f-8439-d560947020b9.png)


Snip of homepage of Admin GUI.

![image](https://user-images.githubusercontent.com/70775749/215344551-6010da22-b06d-4697-9138-234ca2100d1f.png)

Snip of networking tab.

**Comment by nicholaslamon** [comment]
![Image](https://user-images.githubusercontent.com/70776282/215346449-7672982c-7644-4d59-ac17-37fd7c4f9b34.JPG)

Actual router (we love the little screen on it)
