### ISSUE TITLE
Research VPN Access w/ Unifi (Teleport)

### ISSUE THREAD

**Issue by nicholaslamon** [nicholaslamon/CNCS_Capstone#24]
Research how to setup Teleport and how it works:

- Do we need another VPN to hook into it
- Is it standalone
- How to configure clients

**Comment by nrubera** [comment]
We don't need other VPNs to hook into this. It is a standalone VPN client based upon the Unifi user account that we all made. We can configure an internal subnet IP range for VPN clients to connect to.
