### ISSUE TITLE
Network Segmentation

### ISSUE THREAD

**Issue by KyleWebster46** [nicholaslamon/CNCS_Capstone#25]

**Comment by KyleWebster46** [comment]
Segmentation of the network for best security practices.

**Comment by nrubera** [comment]
Network segmentation is complete. I was unable to rename or delete the "default" network but it is configured to be our LAN.

![image](https://user-images.githubusercontent.com/70775749/219899819-418bb174-f767-439f-b41f-4c294aaca421.png)


The WiFi network that any cameras would connect to are located in the LAN segment.

![image](https://user-images.githubusercontent.com/70775749/219900015-078cea30-7eba-4756-8d4a-f3ac2ddda654.png)
