### ISSUE TITLE
Create a List of Hardware Needed / Acquire Hardware

### ISSUE THREAD

**Issue by nrubera** [nicholaslamon/CNCS_Capstone#3]
Reach out to Devin and see about getting help with acquiring the hardware needed for the lab.

Main Hardware:

Ubiquiti Dream Router
2-3 cameras
Eth Cables
Power Cables
Drives for Storage (NAS/Computer operating as a NAS)

**Comment by nicholaslamon** [comment]
Cables will be acquired on an "as needed" basis as we don't know exactly what cables/lengths will be needed yet.
