### ISSUE TITLE
Plan out network topology

### ISSUE THREAD

**Issue by nrubera** [nicholaslamon/CNCS_Capstone#4]
Plan out the overall network topology to show what devices will be where and how they are connected across the network. This will likely be done with either packet tracer or some sort of mind map tool.

**Comment by nicholaslamon** [comment]
Subnet appropriately so that the networks have ample size if expansion on either end is going to happen in the future. #FutureProofing

**Comment by nrubera** [comment]
![image](https://user-images.githubusercontent.com/70775749/195705798-c79abbf3-dfe6-4fc9-a701-87b98f4c2be6.png)
