### ISSUE TITLE
Plan out firewall rules

### ISSUE THREAD

**Issue by nrubera** [nicholaslamon/CNCS_Capstone#5]
Make this network separate from the home network and only allow necessary traffic in/out to ensure it is a closed-loop network.

**Comment by nicholaslamon** [comment]
.

**Comment by KyleWebster46** [comment]
When tasked with coming up with firewall rules for our capstone project centered around Ubiquity and their projects, I think it best to use best standard practices. Below is a very similar diagram to what we are trying to accomplish in the end:

![capstonediag](https://user-images.githubusercontent.com/70776319/196058256-9e96af44-bc7c-4819-8a29-74b2bb2b59e7.PNG)


For our starting, basic firewall rules all traffic in or out will be blocked by default. The Ubiquity dream machine is a device that serves as an all in one solution that encompasses everything from a built-in firewall, router, and cloud key. As a result all firewall rules can be managed from the router’s UI interface. Our goal is to have a way for external users to tunnel into the network and be able to use all of its functionality. To accomplish this there are a few options we can explore. 1) Use a VPN to tunnel into the Ubiquity network.. This option allows us to block all external traffic through the firewall except for the interface through which the VPN uses. This Option also allows us to manage access control security by using the VPN to add, remove, and limit users. Option 2) involves once again blocking all traffic to the Ubiquity network, and white listing all known and trustworthy IPs.
